[rocm-libraries] ROCm/rocm-libraries#1464 (commit 6a024c5)
[hipblaslt] Fix compile definition for lazy loading

## Motivation

When building hipblaslt without lazy loading the following error is
encountered:
```
error: use of undeclared identifier 'ROCBLASLT_TENSILE_LAZY_LOAD'
 1905 |             bool lazyLoad   = ROCBLASLT_TENSILE_LAZY_LOAD;
```

## Technical Details

The compile definition was changed in the build overhaul to only be set
(without a value) when lazy loading is enabled. Now when building by
default `-DROCBLASLT_TENSILE_LAZY_LOAD=1` is added as a definition, and
when compiling with `--no-lazy-library-loading` (through install.sh),
which sets `HIPBLASLT_ENABLE_LAZY_LOAD` internally,
`-DROCBLASLT_TENSILE_LAZY_LOAD=0` is added as a definition.

## Test Plan

- Build both with and without lazy loading, verify the definitions are
added correctly.
- CI testing
- Collaboration with issue creator @yenong-amd for verification.

## Test Result

VERIFIED LOCALLY:
- `./install.sh -c -a gfx950` adds `-DROCBLASLT_TENSILE_LAZY_LOAD=0`
- `./install.sh -c -a gfx950 --no-lazy-library-loading` adds
`-DROCBLASLT_TENSILE_LAZY_LOAD=1`

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.